"""empty message

Revision ID: 2ee4f69c4623
Revises: 661c77af6d0c
Create Date: 2019-11-28 15:53:28.769789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ee4f69c4623'
down_revision = '661c77af6d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'public_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('post', 'public_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'public_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('category', 'public_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
