"""empty message

Revision ID: 9277e0201277
Revises: bff862ed6870
Create Date: 2019-11-29 06:43:14.694164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9277e0201277'
down_revision = 'bff862ed6870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'created_date')
    # ### end Alembic commands ###
